### ISSUE TITLE
Change URL of nsq-lookup dependency to not require authentication

### ISSUE THREAD

**Issue by nunojsferreira** [uphold-forks/nsq.js#11]
Currently `package.json` defines the `nsq-lookup` dependency with a direct link to a commit, using the `git+ssh://` protocol:

https://github.com/uphold-forks/nsq.js/blob/6b699e50c824a1fedb1df7242f5f72c53acced52/package.json#L19

That means that, even though both this repo and `nsq-lookup` are public, any project depending on this one will require SSH keys added to Travis CI in order to clone the repositories and run the test suite.

To fix this, the dependency on `nsq-lookup` should be changed to a `https://` URL, so that cloning can occur without SSH keys.

**Comment by risantos** [comment]
Updated on #15.
[Diff](https://github.com/uphold-forks/nsq.js/pull/15/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L19-R20)
